# Generated by Django 3.2.8 on 2022-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="admin_fee",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
