stages:
  - test
  - sonarqube
  - deploy-dev
  - deploy-prod

linter:
  image: python:3.8
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  when: on_success
  script:
    - black . --check

test:
  image: python:3.8
  stage: test
  variables:
    - DJANGO_SETTINGS_MODULE: paytungan.settings
  before_script:
    - pip install -r requirements.txt
    - python manage.py migrate
  when: on_success
  script:
    - coverage run --include='paytungan/app/*/services*' manage.py test
    - coverage xml -o tests/coverage.xml
    - coverage report -m
  artifacts:
    untracked: true
    when: always
    paths:
      - tests/coverage.xml

deploy-dev:
  image: ruby:2.7.1
  stage: deploy-dev
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - main

sonar-scanner-dev:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarqube
  dependencies:
    - test
  script:
    - cat tests/coverage.xml
    - sonar-scanner
      -Dsonar.host.url=https://pmpl.cs.ui.ac.id/sonarqube
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.branch.target=staging
  allow_failure: true
  except:
    - prod
    - main

sonar-scanner:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarqube
  dependencies:
    - test
  script:
    - cat tests/coverage.xml
    - sonar-scanner
      -Dsonar.host.url=https://pmpl.cs.ui.ac.id/sonarqube
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.login=$SONARQUBE_TOKEN
  allow_failure: true
  only:
    - main
    - prod

deploy:
  stage: deploy-prod
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml
  only:
    - prod
