version: "3.9"

services:
  web:
    image: gcr.io/${PROJECT_ID}/paytungan-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONFIG=${DB_CONFIG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    ports:
      - "8080:8080"
